/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import despacho.Abogados.Abogado;
import despacho.Clientes.Cliente;
import despacho.Procurador;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER;

/**
 *
 * @author gerar
 */
public class ClienteLista extends javax.swing.JPanel {
    private Cliente cliente;
    private boolean abogadoContrario;
    private JPanel panel;
    /**
     * Creates new form AbogadoLista
     */
    public ClienteLista(Cliente cliente,boolean abogadoContrario) {
        initComponents();
        scrollProcurador.setVerticalScrollBarPolicy(VERTICAL_SCROLLBAR_NEVER);
        lblDNI.setText(cliente.getDni());
        lblNombre.setText(cliente.getNombre());
        lblApellidos.setText(cliente.getApellidos());
        Abogado abogado = cliente.getAbogado();
        panelProcurador2.setVisible(abogadoContrario);
        lblProcurador2.setText(abogado.getProcurador().getNombreDespacho());
        lblNombreAbogado.setText(abogado.getNombre());
        lblApellidosAbogado.setText(abogado.getApellidos());
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollProcurador = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnEditarApellidos = new javax.swing.JButton();
        panelProcurador2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblProcurador2 = new javax.swing.JLabel();
        btnProcurador2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombreAbogado = new javax.swing.JLabel();
        lblApellidosAbogado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        btnNombreAbogado = new javax.swing.JButton();
        btnDNI = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        btnApellidosAbogado = new javax.swing.JButton();
        btnEditarNombre = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(315, 169));

        btnEditarApellidos.setText("Editar");
        btnEditarApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarApellidosActionPerformed(evt);
            }
        });

        jLabel9.setText("Procurador:");

        lblProcurador2.setText("jLabel8");

        btnProcurador2.setText("Editar");
        btnProcurador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcuradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProcurador2Layout = new javax.swing.GroupLayout(panelProcurador2);
        panelProcurador2.setLayout(panelProcurador2Layout);
        panelProcurador2Layout.setHorizontalGroup(
            panelProcurador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcurador2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProcurador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcurador2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelProcurador2Layout.setVerticalGroup(
            panelProcurador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProcurador2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelProcurador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblProcurador2)
                    .addComponent(btnProcurador2)))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Abogado");

        jLabel2.setText("Nombre:");

        jLabel1.setText("Nombre:");

        jLabel5.setText("Apellidos:");

        lblNombre.setText("jLabel2");

        lblNombreAbogado.setText("jLabel6");

        lblApellidosAbogado.setText("jLabel7");

        jLabel6.setText("DNI:");

        lblDNI.setText("jLabel7");

        btnNombreAbogado.setText("Editar");
        btnNombreAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreAbogadoActionPerformed(evt);
            }
        });

        btnDNI.setText("Editar");

        jLabel3.setText("Apellidos:");

        lblApellidos.setText("jLabel4");

        btnApellidosAbogado.setText("Editar");
        btnApellidosAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApellidosAbogadoActionPerformed(evt);
            }
        });

        btnEditarNombre.setText("Editar");
        btnEditarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblApellidosAbogado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApellidosAbogado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombreAbogado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNombreAbogado))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblApellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarApellidos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDNI))))
                    .addComponent(panelProcurador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDNI)
                    .addComponent(btnDNI))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre)
                    .addComponent(btnEditarNombre))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblApellidos)
                    .addComponent(btnEditarApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProcurador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombreAbogado)
                    .addComponent(btnNombreAbogado))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblApellidosAbogado)
                    .addComponent(btnApellidosAbogado))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        scrollProcurador.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollProcurador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollProcurador, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNombreActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Nombre");
        if(!"".equals(nombre)){
            cliente.setNombre(nombre);
            lblNombre.setText(nombre);
        }
    }//GEN-LAST:event_btnEditarNombreActionPerformed

    private void btnApellidosAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApellidosAbogadoActionPerformed
        // TODO add your handling code here:
        String apellidos = JOptionPane.showInputDialog(null, "Apellidos");
        if(!"".equals(apellidos)){
            cliente.getAbogado().setApellidos(apellidos);
            lblApellidosAbogado.setText(apellidos);
        }
    }//GEN-LAST:event_btnApellidosAbogadoActionPerformed

    private void btnNombreAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreAbogadoActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Nombre");
        if(!"".equals(nombre)){
            cliente.getAbogado().setNombre(nombre);
            lblNombreAbogado.setText(nombre);
        }
    }//GEN-LAST:event_btnNombreAbogadoActionPerformed

    private void btnProcuradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcuradorActionPerformed
        // TODO add your handling code here:
        String nombreDespacho = JOptionPane.showInputDialog(null, "Procurador");
        Procurador procurador = new Procurador(nombreDespacho);
        if(!"".equals(procurador)){
            cliente.getAbogado().setProcurador(procurador);
            lblProcurador.setText(procurador.getNombreDespacho());
        }
    }//GEN-LAST:event_btnProcuradorActionPerformed

    private void btnEditarApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarApellidosActionPerformed
        // TODO add your handling code here:
        String apellidos = JOptionPane.showInputDialog(null, "Apellidos");
        if(!"".equals(apellidos)){
            cliente.setNombre(apellidos);
            lblApellidos.setText(apellidos);
        }
    }//GEN-LAST:event_btnEditarApellidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApellidosAbogado;
    private javax.swing.JButton btnDNI;
    private javax.swing.JButton btnEditarApellidos;
    private javax.swing.JButton btnEditarNombre;
    private javax.swing.JButton btnNombreAbogado;
    private javax.swing.JButton btnProcurador;
    private javax.swing.JButton btnProcurador1;
    private javax.swing.JButton btnProcurador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidosAbogado;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreAbogado;
    private javax.swing.JLabel lblProcurador;
    private javax.swing.JLabel lblProcurador1;
    private javax.swing.JLabel lblProcurador2;
    private javax.swing.JPanel panelProcurador;
    private javax.swing.JPanel panelProcurador1;
    private javax.swing.JPanel panelProcurador2;
    private javax.swing.JScrollPane scrollProcurador;
    // End of variables declaration//GEN-END:variables
}
